### ISSUE TITLE
First-time usage, CLI hanging during authentication (Linux)

### ISSUE THREAD

**Issue by mattdsteele** [dblock/strava-ruby-cli#1]
👋 Hi!

I'm excited to give this a shot, but I'm having trouble getting authentication to work.

I've created an API id and secret in Strava; installed Ruby 2.5.5 and the CLI through rubygems, but any attempt at authentication hangs after entering my credentials:

Here's where it hangs:

```
matt@penguin:~$ strava run athlete
[2020-05-31 13:00:42] INFO  WEBrick 1.4.2
[2020-05-31 13:00:42] INFO  ruby 2.5.5 (2019-03-15) [aarch64-linux-gnu]
Enter Strava client ID: *****
Enter Strava client secret: ****************************************
[2020-05-31 13:00:52] INFO  WEBrick::HTTPServer#start: pid=12884 port=4242
```

Hitting ctrl+c results in an `^Cerror: Authorization Error` message.

I've tried this on a few Linux workstations (WSL2 Linux container running Debian 10, a "native" Ubuntu 20.04, and a Chromebook crostini container on Debian 10); all with the same result.

Have you seen this error before, maybe I'm missing something in the setup process?

**Comment by mattdsteele** [comment]
For what it's worth, I can authenticate and pull info successfully with `strava-ruby-client` directly. Thanks again for putting these together :)

**Comment by dblock** [comment]
I think this just wasn't properly implemented on linux, the code [calls open](https://github.com/dblock/strava-ruby-cli/blob/46ab16e4109da9146c2a44257471dc5fc0aca804/lib/cli/auth.rb#L65), but that only works on OSX. There's an [SO](https://stackoverflow.com/questions/152699/open-the-default-browser-in-ruby/152996) that recommends `launchy` to make it work. 

Want to try fixing this?
